# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daniel Sprockett, PhD
email: daniel.sprockett@gmail.com
description: Assistant Professor at Wake Health
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danielsprockett.github.io/" # the base hostname & protocol for your site
github_username:  danielsprockett
paginate: 5
theme-dark: false #Set to true to change to dark website theme

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown

# SYNC with
# cd /Users/daniel/_site/danielsprockett.github.io
# git add --all
# git commit -m "add post"
# git push -u origin master

